# Analytics
analytics:
  provider               : "google-analytics-4" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          : "G-SL0KCDQVQ1"
