  giscus:
    repo                 : "LTzycLT/ltzyclt.github.io"
    repo_id              : "R_kgDOPf4iKA"
    category             : "General"
    category_id          : "DIC_kwDOPf4iKM4C3gDj"
    mapping              : "pathname"
    strict               : "0"
    reactions_enabled    : "1"
    emit_metadata        : "0"
    input_position       : "bottom"
    theme                : "preferred_color_scheme"
    lang                 : "en"
